### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by JP1128** [thelukechen/arcade-chess#2]
You could probably organize the assets better by putting them in sub-directories.
```
resources
|---images
|     |---icons
|     |     |--- ...
|     |---pieces
|     |     |--- black
|     |     |      |--- ...
|     |     |--- white
|     |     |      |--- ...
```

**Comment by JP1128** [comment]
Also, instead of putting all the classes in one directory, divide them up

**Comment by thelukechen** [comment]
Class and resources files now in sub-directories
